// Made By Damian Sclafani
package MemoryMerge;
import java.util.ArrayList;

public class TBWGenerator {
    private ArrayList<String> characters = new ArrayList<>();

    public TBWGenerator() {
        createArray();
    }
    
    public String generateAny() {
        int rand = (int)(Math.random()*characters.size());
        return characters.get(rand);
    }

    public String generateEquipment() {
        int rand = (int)(Math.random()*183);
        return characters.get(rand);
    }

    private void createArray() {
        characters.add("E1. Trampoline");
        characters.add("E2. Sleeping Song");
        characters.add("E3. Zap");
        characters.add("E4. Bolt");
        characters.add("E5. Lightning Bolt");
        characters.add("E6. Booster");
        characters.add("E7. Mana Pump");
        characters.add("E8. Baseball");
        characters.add("E9. Darkness");
        characters.add("E10. Mimic Magic");
        characters.add("E11. Bull Rush");
        characters.add("E12. The Summoning");
        characters.add("E13. Magic Hand");
        characters.add("E14. Rat Poison");
        characters.add("E15. Pills");
        characters.add("E16. Medkit");
        characters.add("E17. Bandage");
        characters.add("E18. Doc Kit");
        characters.add("E19. The Return");
        characters.add("E20. Vacuum Cleaner");
        characters.add("E21. Gamble");
        characters.add("E22. Mega Fertilizer");
        characters.add("E23. Photosynthesis");
        characters.add("E24. Sticky Bomb");
        characters.add("E25. Iron Armor");
        characters.add("E26. Steel Armor");
        characters.add("E27. Magic Shield");
        characters.add("E28. Root Shield");
        characters.add("E29. Magnet");
        characters.add("E30. Eruption");
        characters.add("E31. Coffee Machine");
        characters.add("E32. Green Lightning");
        characters.add("E33. EMP Grenade");
        characters.add("E34. Negative Energy");
        characters.add("E35. Rocket Jets");
        characters.add("E36. Teleporter");
        characters.add("E37. Creation Spell");
        characters.add("E38. Triple Lightning");
        characters.add("E39. Big Bomb");
        characters.add("E40. Energy Drink");
        characters.add("E41. Birdification");
        characters.add("E42. Sky Laser");
        characters.add("E43. Armory");
        characters.add("E44. Sky Light; Storm");
        characters.add("E45. Sky Light; Slash");
        characters.add("E46. Frost Breath");
        characters.add("E47. Training");
        characters.add("E48. Atom Bomb");
        characters.add("E49. Dance Battle");
        characters.add("E50. Sky Light; Ganym");
        characters.add("E51. Rescue");
        characters.add("E52. Flashlight");
        characters.add("E53. Gas Grenade");
        characters.add("E54. Magic Malfunction");
        characters.add("E55. Furious Winds");
        characters.add("E56. Earth Shatter");
        characters.add("E57. Ratify");
        characters.add("E58. Bag of Rats");
        characters.add("E59. Boomerang");
        characters.add("E60. Stage");
        characters.add("E61. Christmas Gifts");
        characters.add("E62. Rocket Fist");
        characters.add("E63. Thunder Bolt");
        characters.add("E64. Geometry");
        characters.add("E65. Trigonometry");
        characters.add("E66. Calculus");
        characters.add("E67. Algebra");
        characters.add("E68. Earthquake");
        characters.add("E69. Halloween Candy");
        characters.add("E70. Smoke Machine");
        characters.add("E71. Shock Caller");
        characters.add("E72. Shock's Package");
        characters.add("E73. Cloning Machine");
        characters.add("E74. Ammo Box");
        characters.add("E75. Smoke Bomb");
        characters.add("E76. Mind Control");
        characters.add("E77. Fooled");
        characters.add("E78. Rock, Paper, Scissors");
        characters.add("E79. Pepper Spray");
        characters.add("E80. Fresh Meat");
        characters.add("E81. Cable");
        characters.add("E82. Vine Wrap");
        characters.add("E83. Reflector Shield");
        characters.add("E84. Medical Grenades");
        characters.add("E85. Electrolight");
        characters.add("E86. Disease");
        characters.add("E87. Time to Shine");
        characters.add("E88. Chisel");
        characters.add("E89. Beaker");
        characters.add("E90. Sprout");
        characters.add("E91. Padlock");
        characters.add("E92. Battlecry");
        characters.add("E93. Spiked Hook");
        characters.add("E94. Freeze");
        characters.add("E95. Mana Shield");
        characters.add("E96. Flameroast");
        characters.add("E97. Duelist");
        characters.add("E98. Snake Cage");
        characters.add("E99. Witch Potion");
        characters.add("E100. Crazy Chemicals");
        characters.add("E101. Duel");
        characters.add("E102. Tournament");
        characters.add("E103. Aggressive Current");
        characters.add("E104. Zombify");
        characters.add("E105. Snake! Eagle! Person!");
        characters.add("E106. Brawl");
        characters.add("E107. Double Dice");
        characters.add("E108. Necromius, The Legendary Blade");
        characters.add("E109. Rattle");
        characters.add("E110. Battleheart");
        characters.add("E111. Leech Life");
        characters.add("E112. Fireball");
        characters.add("E113. Blazing Arrow");
        characters.add("E114. Geyser");
        characters.add("E115. Twig of Gifting");
        characters.add("E116. Sky Light; Snowball");
        characters.add("E117. Throwing Knife");
        characters.add("E118. Sky Light; Mecha-Hawk");
        characters.add("E119. Battlerage");
        characters.add("E120. Lunge");
        characters.add("E121. Syringe");
        characters.add("E122. Bag of Bones");
        characters.add("E123. Blessings");
        characters.add("E124. Minions!");
        characters.add("E125. Refreshment");
        characters.add("E126. Necro Arrow");
        characters.add("E127. Unprepared Medkit");
        characters.add("E128. Cupid's Arrow");
        characters.add("E129. Hammer Toss");
        characters.add("E130. Life Drain");
        characters.add("E131. Vampiric");
        characters.add("E132. Care Package");
        characters.add("E133. Wish");
        characters.add("E134. Inner Beast");
        characters.add("E135. Stake");
        characters.add("E136. Horn");
        characters.add("E137. Sacred Spell");
        characters.add("E138. Goop Spray");
        characters.add("E139. Secret Relic");
        characters.add("E140. Forgotten Relic");
        characters.add("E141. Ancient Relic");
        characters.add("E142. Overgrowth");
        characters.add("E143. Neutral Energy");
        characters.add("E144. Pocket Sand");
        characters.add("E145. Leap");
        characters.add("E146. Sprint");
        characters.add("E147. Bet");
        characters.add("E148. Recreate");
        characters.add("E149. Crushing Blow");
        characters.add("E150. Air Strike");
        characters.add("E151. Storm Cloud");
        characters.add("E152. Wave");
        characters.add("E153. Positive Energy");
        characters.add("E154. Arcane Bomb");
        characters.add("E155. Inferno");
        characters.add("E156. Earthen Might");
        characters.add("E157. Regrow");
        characters.add("E158. Blood Burst");
        characters.add("E159. Yellow Potion");
        characters.add("E160. Gray Potion");
        characters.add("E161. Red Potion");
        characters.add("E162. Purple Potion");
        characters.add("E163. Orange Potion");
        characters.add("E164. Green Potion");
        characters.add("E165. Blue Potion");
        characters.add("E166. White Potion");
        characters.add("E167. Black Potion");
        characters.add("E168. Pink Potion");
        characters.add("E169. Rainbow Potion");
        characters.add("E170. Gust");
        characters.add("E171. Sunshine");
        characters.add("E172. Dark Pact");
        characters.add("E173. Icicles");
        characters.add("E174. Goop Shield");
        characters.add("E175. Slam");
        characters.add("E176. Force Field");
        characters.add("E177. River");
        characters.add("E178. Elemental Burst");
        characters.add("E179. Telekinesis");
        characters.add("E180. Sap");
        characters.add("E181. Laser Pointer");
        characters.add("E182. Molten Armor");
        characters.add("E183. Scope");
        characters.add("S1. Knight");
        characters.add("S2. Valkyrie");
        characters.add("S3. Heavy");
        characters.add("S4. Archer");
        characters.add("S5. Mage");
        characters.add("S6. Spy");
        characters.add("S7. Shieldman");
        characters.add("S8. Shifter");
        characters.add("S9. Bomber");
        characters.add("S10. Basic Giant");
        characters.add("S11. Hatchetman");
        characters.add("S12. Sparrow");
        characters.add("1. Psycho");
        characters.add("2. Queen");
        // Continue with the rest of the unlockable units
        characters.add("FF1. Lionheart Knight");
        characters.add("FF2. Enslaved Giant");
        // Continue with the rest of the full force characters
    }
}
